### ISSUE TITLE
PFAddr IPv4 regex matching IPv6

### ISSUE THREAD

**Issue by nahun** [dotpy/py-pf#4]
The PFAddr IPv4 regex is matching IPv6 addresses if the first group of hex digits in the IPv6 address are 0-9. If the first group has letters, it matches IPv6 correctly.

Working example:
```
>>> import pf
>>> test = pf.PFAddr('fe80::a00:27ff:fee2:7dcc')
>>> test.addr
'fe80::a00:27ff:fee2:7dcc'
>>> test.af
24
>>> test.mask
'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff'
```
Not working example:
```
>>> import pf
>>> test = pf.PFAddr('2512:652:de34:4405::1')
>>> test.addr
'2512'
>>> test.af
2
>>> test.mask
'255.255.255.255'
```

Modifying the regex in rule.py on line 271 to be the following works:
`(?P<ipv4>[0-9.]+)(?:/(?P<mask4>\d+))(?!:)?|`
This adds a negative lookahead for any "**:**" characters at the end. I can submit a pull request if needed, but I honestly don't know if thats the best regex fix.

**Comment by nahun** [comment]
I realized PFTableAddr probably has the same issue. I just tested and it does.

**Comment by dotpy** [comment]
Thanks a lot for pointing out this bug.
I fixed it by modifying the IPv4 regexp (in both PFAddr and PFTableAddr) to:
```
"[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"
```
