### ISSUE TITLE
Filter in get_tables() and get_tstats()

### ISSUE THREAD

**Issue by nahun** [dotpy/py-pf#5]
The filter in get_tables() and get_tstats() (maybe others too) doesn't seem to work. They always return all stats or tables. Example for get_tstats():
```
>>> import pf
>>> pfilter = pf.PacketFilter()
>>> table = pfilter.get_tables()[0]
>>> table.name
'LAN_VPN'
>>> stats = pfilter.get_tstats(table)
>>> stats
(<pf.table.PFTStats object at 0x1f01a5bc7d10>, <pf.table.PFTStats object at 0x1f01a5bc7bd0>, <pf.table.PFTStats object at 0x1f01a5bc7d50>)
```
Hopefully I'm not misunderstanding how the filter works.

**Comment by dotpy** [comment]
Actually I did misunderstand how the filter works at the kernel level.
Digging the kernel code (`/usr/src/sys/net/pf_table.c`) I found out that only the `anchor` attribute of the `filter` table is taken into account; so the `filter` parameter only allows you to specify the anchor in which the tables can be found, but not a single table (by name).

For example:
```
>>> import pf
>>> table1 = pf.PFTable("web_srv", "10.0.1.20", "10.0.1.21", "10.0.1.22",
...                     flags=pf.PFR_TFLAG_PERSIST, anchor="/foo")
>>> table2 = pf.PFTable("dns_srv", "10.0.1.23", "10.0.1.24",
...                     flags=pf.PFR_TFLAG_PERSIST, anchor="/foo")
>>> pfilter = pf.PacketFilter()
>>> pfilter.add_tables(table1, table2)
2
>>> pfilter.get_tables(pf.PFTable(anchor="/foo"))
(<pf.table.PFTable object at 0x146b58e7c450>, <pf.table.PFTable object at 0x146b58e7c590>)
```

The same thing using `pfctl(8)`:

```
# pfctl -a foo -t web_srv -T add 10.0.1.20 10.0.1.21 10.0.1.22
# pfctl -a foo -t dns_srv -T add 10.0.1.23 10.0.1.24
# pfctl -sT -a foo
web_srv
dns_srv
```

So I fixed the `PacketFilter` code to only take the `filter.anchor` attribute into account.
Maybe I should replace the `filter` argument by a simpler `anchor` string parameter, but I didn't want to change the API for now.
