### ISSUE TITLE
Documentation for PFPool seem incorrect

### ISSUE THREAD

**Issue by nahun** [dotpy/py-pf#6]
Nothing big, but the docs for [PFPool](http://www.kernel-panic.it/programming/py-pf/pf6.html#pf-6.2.1) have the PFAddr object under the attribute PFPool.pool, but it seems to be under PFPool.addr in [rule.py](https://github.com/dotpy/py-pf/blob/master/pf/rule.py#L503)

**Comment by dotpy** [comment]
Thanks for pointing this out! Docs corrected.
