### ISSUE TITLE
OpenBSD 6.2 Support

### ISSUE THREAD

**Issue by nahun** [dotpy/py-pf#7]
There have been [some changes](https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/sys/net/pfvar.h.diff?r1=1.466&r2=1.434&f=h). Here are a couple quick ones that affected me. I'm sure there are more and since I don't know C well enough, my fixes aren't great either.

- Added field 'states_halfopen' in pf_status struct. Added in pfvar.h [this commit](https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/sys/net/pfvar.h.diff?r1=1.463&r2=1.464&f=h).
- Added fields in pf_rule struct. Added in pfvar.h in [this commit](https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/sys/net/pfvar.h.diff?r1=1.437&r2=1.438&f=h).

Diff for py-pf that at least lets me get status and rules:
```diff
diff --git a/pf/_struct.py b/pf/_struct.py
index f1859df..165330d 100644
--- a/pf/_struct.py
+++ b/pf/_struct.py
@@ -78,6 +78,7 @@ class pf_status(Structure):       # From /usr/include/net/pfvar.h
                                ("since",             c_int64),       # time_t
                 ("running",           c_uint32),
                 ("states",            c_uint32),
+                ("states_halfopen",   c_uint32),
                 ("src_nodes",         c_uint32),
                 ("debug",             c_uint32),
                 ("hostid",            c_uint32),
@@ -345,7 +346,10 @@ class pf_rule(Structure):               # From /usr/include/net/pfvar.h
                 ("rcvifnot",          c_uint8),
                 ("pad",               c_uint8 * 2),
                 ("divert",            _divert),
-                ("divert_packet",     _divert)]
+                ("divert_packet",     _divert),
+                ("gcle",              c_void_p),
+                ("ruleset",           c_void_p),
+                ("exptime",           c_int64)]       # time_t
 
 
 class pfioc_rule(Structure):      # From /usr/include/net/pfvar.h
```

**Comment by dotpy** [comment]
Hi Nathan,
Thanks a lot for the diff.
I've spotted a few other changes, but for the moment, I'm getting some errors during tests...
So, I just wanted to give you an update, I'm working on it.

**Comment by dotpy** [comment]
Hi Nathan,
Just to give you an update, I've imported the changes but there are still a couple issues:

- The status uptime (PFStatus.since) is now calculated since the machine uptime, not anymore since the epoch, using "clock_gettime(CLOCK_UPTIME, &uptime)", which is not available in native Python (not even Python 3)
- loading queues corrupts kernel data in some way making all successive commits fail

I'm working on these issues, and I'll let you know as soon as they're solved.
Cheers,
Daniele

**Comment by dotpy** [comment]
Hi Nathan,
Everything should work fine now with OpenBSD 6.2.
Some little changes were made to the queueing classes.
I'll update the doc as soon as possible.
Thanks again for your help!
Cheers,
Daniele
