### ISSUE TITLE
Have statistics for labels (pfctl -sl)

### ISSUE THREAD

**Issue by jaywax** [dotpy/py-pf#9]
Hello,
Would be nice if we could have statistics for labels rules : 
`-s labels       Show per-rule statistics (label, evaluations,
                             packets total, bytes total, packets in, bytes in,
                             packets out, bytes out, state creations) of
                             filter rules with labels, useful for accounting.
                             If -R id is specified as well, only the
`

**Comment by dotpy** [comment]
Hi,

Here's a sample script that does exactly what `pfctl -sl` does:

```
#!/usr/bin/env python

import pf

filter = pf.PacketFilter()
ruleset = filter.get_ruleset()
for rule in ruleset.rules:
    if rule.label:
        stats = (rule.evaluations,
                 rule.packets[0] + rule.packets[1],
                 rule.bytes[0] + rule.bytes[1],
                 rule.packets[0],
                 rule.bytes[0],
                 rule.packets[1],
                 rule.bytes[1],
                 rule.states_tot)
        print "{} {} {} {} {} {} {} {} {}".format(rule.label, *stats)
```

Best regards,
  Daniele

**Comment by jaywax** [comment]
Hello Daniele,

Thanks for you quick feelback.

Best regards.
